Experiment 1, batch size is 16, learning rate is 0.1.
main(
  batch_size : int = 16
  test_batch_size : int = 1000
  epochs : int = 0
  lr : float = 0.1
  gamma : float = 0.7
  no_cuda : bool = False
  dry_run : bool = False
  seed : int = 1
  log_interval : int = 10
  save_model : bool = False
)

Experiment 2, batch size is 16, learning rate is 0.5.
main(
  batch_size : int = 16
  test_batch_size : int = 1000
  epochs : int = 0
  lr : float = 0.5
  gamma : float = 0.7
  no_cuda : bool = False
  dry_run : bool = False
  seed : int = 1
  log_interval : int = 10
  save_model : bool = False
)

Experiment 3, batch size is 16, learning rate is 1.0.
main(
  batch_size : int = 16
  test_batch_size : int = 1000
  epochs : int = 0
  lr : float = 1.0
  gamma : float = 0.7
  no_cuda : bool = False
  dry_run : bool = False
  seed : int = 1
  log_interval : int = 10
  save_model : bool = False
)

Experiment 4, batch size is 32, learning rate is 0.1.
main(
  batch_size : int = 32
  test_batch_size : int = 1000
  epochs : int = 0
  lr : float = 0.1
  gamma : float = 0.7
  no_cuda : bool = False
  dry_run : bool = False
  seed : int = 1
  log_interval : int = 10
  save_model : bool = False
)

Experiment 5, batch size is 32, learning rate is 0.5.
main(
  batch_size : int = 32
  test_batch_size : int = 1000
  epochs : int = 0
  lr : float = 0.5
  gamma : float = 0.7
  no_cuda : bool = False
  dry_run : bool = False
  seed : int = 1
  log_interval : int = 10
  save_model : bool = False
)

Experiment 6, batch size is 32, learning rate is 1.0.
main(
  batch_size : int = 32
  test_batch_size : int = 1000
  epochs : int = 0
  lr : float = 1.0
  gamma : float = 0.7
  no_cuda : bool = False
  dry_run : bool = False
  seed : int = 1
  log_interval : int = 10
  save_model : bool = False
)

Experiment 7, batch size is 64, learning rate is 0.1.
main(
  batch_size : int = 64
  test_batch_size : int = 1000
  epochs : int = 0
  lr : float = 0.1
  gamma : float = 0.7
  no_cuda : bool = False
  dry_run : bool = False
  seed : int = 1
  log_interval : int = 10
  save_model : bool = False
)

Experiment 8, batch size is 64, learning rate is 0.5.
main(
  batch_size : int = 64
  test_batch_size : int = 1000
  epochs : int = 0
  lr : float = 0.5
  gamma : float = 0.7
  no_cuda : bool = False
  dry_run : bool = False
  seed : int = 1
  log_interval : int = 10
  save_model : bool = False
)

Experiment 9, batch size is 64, learning rate is 1.0.
main(
  batch_size : int = 64
  test_batch_size : int = 1000
  epochs : int = 0
  lr : float = 1.0
  gamma : float = 0.7
  no_cuda : bool = False
  dry_run : bool = False
  seed : int = 1
  log_interval : int = 10
  save_model : bool = False
)

