Experiment 1, batch size is 16, learning rate is 0.1.
main <- batch_size=16, test_batch_size=1000, epochs=0, lr=0.1, gamma=0.7, no_cuda=False, dry_run=False, seed=1, log_interval=10, save_model=False

Experiment 2, batch size is 16, learning rate is 0.5.
main <- batch_size=16, test_batch_size=1000, epochs=0, lr=0.5, gamma=0.7, no_cuda=False, dry_run=False, seed=1, log_interval=10, save_model=False

Experiment 3, batch size is 16, learning rate is 1.0.
main <- batch_size=16, test_batch_size=1000, epochs=0, lr=1.0, gamma=0.7, no_cuda=False, dry_run=False, seed=1, log_interval=10, save_model=False

Experiment 4, batch size is 32, learning rate is 0.1.
main <- batch_size=32, test_batch_size=1000, epochs=0, lr=0.1, gamma=0.7, no_cuda=False, dry_run=False, seed=1, log_interval=10, save_model=False

Experiment 5, batch size is 32, learning rate is 0.5.
main <- batch_size=32, test_batch_size=1000, epochs=0, lr=0.5, gamma=0.7, no_cuda=False, dry_run=False, seed=1, log_interval=10, save_model=False

Experiment 6, batch size is 32, learning rate is 1.0.
main <- batch_size=32, test_batch_size=1000, epochs=0, lr=1.0, gamma=0.7, no_cuda=False, dry_run=False, seed=1, log_interval=10, save_model=False

Experiment 7, batch size is 64, learning rate is 0.1.
main <- batch_size=64, test_batch_size=1000, epochs=0, lr=0.1, gamma=0.7, no_cuda=False, dry_run=False, seed=1, log_interval=10, save_model=False

Experiment 8, batch size is 64, learning rate is 0.5.
main <- batch_size=64, test_batch_size=1000, epochs=0, lr=0.5, gamma=0.7, no_cuda=False, dry_run=False, seed=1, log_interval=10, save_model=False

Experiment 9, batch size is 64, learning rate is 1.0.
main <- batch_size=64, test_batch_size=1000, epochs=0, lr=1.0, gamma=0.7, no_cuda=False, dry_run=False, seed=1, log_interval=10, save_model=False

