func(
  str_arg : str = string
  int_arg : int = 1
  dict_arg : NoneType = None
  list_int_arg : NoneType = None
  list_str_arg : NoneType = None
  bool_arg : bool = False
  tuple_arg : NoneType = None
)
String argument - type: <class 'str'>, val: string
Integer argument - type: <class 'int'>, val: 1
Dictionary argument - type: <class 'NoneType'>, val: None
List of ints argument - type: <class 'NoneType'>, val: None
List of strings argument - type: <class 'NoneType'>, val: None
Boolean argument - type: <class 'bool'>, val: False
Tuple of (int, float, str) - type: <class 'NoneType'>, val: None
