run(
  stages : list = ['download', 'preprocess', 'train', 'evaluate', 'analyze']
)
output(
  folder : str = /tmp/output
)
Making output folder /tmp/output.
Switched working directory to /tmp/output
download(
  folder : str = /data/raw
)
STAGE: DOWNLOAD
Downloading data to /data/raw

preprocess(
  src_folder : str = /data/raw
  dst_folder : str = /data/processed
)
STAGE: PREPROCESS
Preprocessing /data/raw into /data/processed

train(
  folder : str = /data/processed/train/
  epochs : int = 50
  lr : float = 0.001
  model_type : str = conv
  model_path : str = checkpoints/model.pth
)
STAGE: TRAIN
Training model conv on data in /data/processed/train/ for 50 epochs, with learning rate of 0.001

evaluate(
  model_path : str = checkpoints/model.pth
  folder : str = /data/processed/test/
  results_folder : str = ./results
)
STAGE: EVALUATE
Evaluating model checkpoints/model.pth on /data/processed/test/, saving results to ./results

analyze(
  results_folder : str = ./results
)
STAGE: ANALYZE
Generating plots for ./results

Returning to original folder
